version: '2'
services:
  frontend:
    image: dtdemos/dt-orders-frontend:1
    ports:
      - "80:8080"
    environment:
      SERVICES_PORT: "8080"
      DT_APPLICATIONID: "frontend"
  customer:
    image: dtdemos/dt-orders-customer-service:1
    ports:
      - "8081:8080"
  catalog:
    image: dtdemos/dt-orders-catalog-service:1
    ports:
      - "8082:8080"
  order:
    image: dtdemos/dt-orders-order-service:1
    ports:
      - "8083:8080"
    environment:
      CUSTOMER_SERVICE_PORT: "8080"
      CATALOG_SERVICE_PORT: "8080"
